# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Fizzly' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Fizzly
  pod 'Alamofire', '~> 4.6.0'

  target 'FizzlyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FizzlyUITests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Swifter', '~> 1.3.3'
    pod 'XCTest-Gherkin', '~> 0.13.2'
  end
  
  post_install do |installer|
      installer.pods_project.targets.each do |target|
          if target.name == 'Swifter'
              target.build_configurations.each do |config|
                  config.build_settings['SWIFT_VERSION'] = '3.2'
              end
          end
      end
  end
end
